import type { AgentManifest, AuditEvent, Candidate, Job, MatchResult, Notification, SkillGraphData, Source, WorkflowRun } from "./types";

export const demoAgent: AgentManifest = {
  agent_id: "global-part-time",
  name: "全球兼职职位匹配 Agent",
  version: "0.2.0",
  description: "从已批准 Feed 同步职位，并为主动订阅的候选人生成可审计推荐。",
  tags: ["jobs", "matching", "compliance"],
  owner: "local",
  actions: [
    { name: "list_sources", description: "列出已登记来源", mode: "read", risk_level: "low", requires_idempotency_key: false, input_schema: {} },
    { name: "sync_source", description: "同步一个已批准的结构化职位 Feed", mode: "write", risk_level: "medium", requires_idempotency_key: true, input_schema: { required: ["source_id", "jobs"] } },
    { name: "validate_job", description: "读取确定性风险与质量校验结果", mode: "read", risk_level: "low", requires_idempotency_key: false, input_schema: { required: ["job_id"] } },
    { name: "find_matches", description: "为已订阅候选人执行硬过滤和匹配排序", mode: "write", risk_level: "low", requires_idempotency_key: true, input_schema: { required: ["candidate_id"] } },
    { name: "draft_digest", description: "生成最多五个职位的通知草稿", mode: "write", risk_level: "medium", requires_idempotency_key: true, input_schema: { required: ["candidate_id", "match_ids"] } },
    { name: "request_approval", description: "为高风险动作创建人工审批任务", mode: "write", risk_level: "high", requires_idempotency_key: true, input_schema: { required: ["action", "target_id"] } },
    { name: "send_digest", description: "发送已经批准的通知草稿", mode: "write", risk_level: "high", requires_idempotency_key: true, input_schema: { required: ["notification_id"] } },
  ],
};

export const demoSources: Source[] = [
  { id: "src_001", name: "Remote AI Partner Feed", source_type: "partner_feed", base_url: "https://feed.example.com", review_status: "approved", enabled: true, rate_limit: "60/hour", updated_at: "2026-07-15T09:42:00Z" },
  { id: "src_002", name: "Greenhouse Public ATS", source_type: "ats", base_url: "https://boards.greenhouse.io", review_status: "approved", enabled: true, rate_limit: "30/hour", updated_at: "2026-07-15T09:18:00Z" },
  { id: "src_003", name: "Design Studio Careers", source_type: "company_page", base_url: "https://design.example.org", review_status: "pending", enabled: false, rate_limit: "12/hour", updated_at: "2026-07-15T08:56:00Z" },
  { id: "src_004", name: "APAC Contract RSS", source_type: "rss", base_url: "https://jobs.example.net/rss", review_status: "approved", enabled: true, rate_limit: "24/hour", updated_at: "2026-07-15T08:31:00Z" },
];

export const demoJobs: Job[] = [
  {
    id: "job_001",
    title_original: "AI Evaluation Specialist",
    title_zh: "AI 评估专家",
    company_name: "Northstar Labs",
    description_original: "评估 AI 模型输出，按照书面标准记录问题并提供清晰、可复核的反馈。",
    employment_type: "part_time",
    work_mode: "remote",
    countries_allowed: ["CN", "SG"],
    timezone_requirements: ["UTC+08:00"],
    languages: ["中文", "English"],
    skills: ["AI evaluation", "Quality assurance", "Written communication"],
    categories: ["AI", "Data quality"],
    hours_per_week_min: 10,
    hours_per_week_max: 20,
    risk_level: "low",
    risk_score: 0.08,
    quality_score: 0.94,
    status: "active",
    compensation_min: 18,
    compensation_max: 26,
    compensation_currency: "USD",
    compensation_period: "hour",
    canonical_url: "https://example.com/jobs/ai-evaluation-specialist",
    published_at: "2026-07-15T09:20:00Z",
    source_id: "src_001",
    review_status: "not_required",
  },
  { id: "job_002", title_original: "Python Data Reviewer", company_name: "Atlas Data Co.", work_mode: "remote", countries_allowed: ["GLOBAL"], risk_level: "low", risk_score: 0.11, quality_score: 0.89, status: "active", compensation_min: 16, compensation_max: 24, compensation_currency: "USD", review_status: "approved", reviewed_by: "operator@agenthub.local", reviewed_at: "2026-07-14T16:30:00Z", review_note: "信息完整，来源可靠" },
  { id: "job_003", title_original: "Bilingual Content Analyst", company_name: "LinguaWorks", work_mode: "remote", countries_allowed: ["CN", "JP"], risk_level: "medium", risk_score: 0.32, quality_score: 0.73, status: "pending_review", compensation_min: 14, compensation_max: 20, compensation_currency: "USD", review_status: "pending", risk_signals: ["薪酬范围低于市场中位数", "公司信息不完整", "职位描述缺少具体职责"] },
  { id: "job_004", title_original: "Part-time Product Designer", company_name: "Studio Commons", work_mode: "hybrid", countries_allowed: ["SG"], risk_level: "low", risk_score: 0.06, quality_score: 0.91, status: "active", compensation_min: 28, compensation_max: 40, compensation_currency: "USD", review_status: "not_required" },
  { id: "job_005", title_original: "Remote Task Assistant", company_name: "Unknown Merchant", work_mode: "remote", countries_allowed: ["GLOBAL"], risk_level: "high", risk_score: 0.81, quality_score: 0.28, status: "rejected", compensation_min: 60, compensation_max: 100, compensation_currency: "USD", review_status: "rejected", reviewed_by: "operator@agenthub.local", reviewed_at: "2026-07-15T09:34:00Z", review_note: "薪酬异常偏高，公司信息无法核实，疑似欺诈" },
];

export const demoAudits: AuditEvent[] = [
  { id: 71, event: "notification.sent", entity_kind: "notification", entity_id: "ntf_2401", actor: "scheduler", details: { provider: "simulation" }, created_at: "2026-07-15T09:46:00Z" },
  { id: 70, event: "matches.run", entity_kind: "candidate", entity_id: "cand_0188", actor: "scheduler", details: { matched: 12, filtered: 31 }, created_at: "2026-07-15T09:41:00Z" },
  { id: 69, event: "job.reviewed", entity_kind: "job", entity_id: "job_003", actor: "operator@agenthub.local", details: { approved: false }, created_at: "2026-07-15T09:34:00Z" },
  { id: 68, event: "source.synced", entity_kind: "source", entity_id: "src_001", actor: "worker", details: { received: 48 }, created_at: "2026-07-15T09:22:00Z" },
  { id: 67, event: "job.imported", entity_kind: "job", entity_id: "job_0902", actor: "worker", details: { risk: "low" }, created_at: "2026-07-15T09:20:00Z" },
  { id: 66, event: "approval.requested", entity_kind: "approval", entity_id: "apr_084", actor: "operator", details: { action: "send_digest" }, created_at: "2026-07-15T09:08:00Z" },
];

export const demoSkillGraph: SkillGraphData = {
  nodes: [
    // Categories
    { id: "前端开发", type: "category" },
    { id: "后端开发", type: "category" },
    { id: "数据库", type: "category" },
    { id: "容器与云", type: "category" },
    { id: "移动开发", type: "category" },
    { id: "数据与AI", type: "category" },
    // 前端开发 skills
    { id: "React", type: "skill" },
    { id: "Vue", type: "skill" },
    { id: "TypeScript", type: "skill" },
    { id: "Next.js", type: "skill" },
    { id: "Tailwind CSS", type: "skill" },
    // 后端开发 skills
    { id: "Python", type: "skill" },
    { id: "Java", type: "skill" },
    { id: "Go", type: "skill" },
    { id: "Node.js", type: "skill" },
    { id: "Rust", type: "skill" },
    // 数据库 skills
    { id: "PostgreSQL", type: "skill" },
    { id: "MySQL", type: "skill" },
    { id: "MongoDB", type: "skill" },
    { id: "Redis", type: "skill" },
    // 容器与云 skills
    { id: "Docker", type: "skill" },
    { id: "Kubernetes", type: "skill" },
    { id: "AWS", type: "skill" },
    // 移动开发 skills
    { id: "React Native", type: "skill" },
    { id: "Flutter", type: "skill" },
    { id: "Swift", type: "skill" },
    // 数据与AI skills
    { id: "TensorFlow", type: "skill" },
    { id: "PyTorch", type: "skill" },
    { id: "Pandas", type: "skill" },
    // Aliases
    { id: "React.js", type: "alias" },
    { id: "ReactJS", type: "alias" },
    { id: "Vue.js", type: "alias" },
    { id: "TS", type: "alias" },
    { id: "NextJS", type: "alias" },
    { id: "Golang", type: "alias" },
    { id: "NodeJS", type: "alias" },
    { id: "Postgres", type: "alias" },
    { id: "Mongo", type: "alias" },
    { id: "K8s", type: "alias" },
    { id: "RN", type: "alias" },
    { id: "TF", type: "alias" },
  ],
  links: [
    // CHILD_OF: 前端开发
    { source: "React", target: "前端开发", type: "CHILD_OF" },
    { source: "Vue", target: "前端开发", type: "CHILD_OF" },
    { source: "TypeScript", target: "前端开发", type: "CHILD_OF" },
    { source: "Next.js", target: "前端开发", type: "CHILD_OF" },
    { source: "Tailwind CSS", target: "前端开发", type: "CHILD_OF" },
    // CHILD_OF: 后端开发
    { source: "Python", target: "后端开发", type: "CHILD_OF" },
    { source: "Java", target: "后端开发", type: "CHILD_OF" },
    { source: "Go", target: "后端开发", type: "CHILD_OF" },
    { source: "Node.js", target: "后端开发", type: "CHILD_OF" },
    { source: "Rust", target: "后端开发", type: "CHILD_OF" },
    // CHILD_OF: 数据库
    { source: "PostgreSQL", target: "数据库", type: "CHILD_OF" },
    { source: "MySQL", target: "数据库", type: "CHILD_OF" },
    { source: "MongoDB", target: "数据库", type: "CHILD_OF" },
    { source: "Redis", target: "数据库", type: "CHILD_OF" },
    // CHILD_OF: 容器与云
    { source: "Docker", target: "容器与云", type: "CHILD_OF" },
    { source: "Kubernetes", target: "容器与云", type: "CHILD_OF" },
    { source: "AWS", target: "容器与云", type: "CHILD_OF" },
    // CHILD_OF: 移动开发
    { source: "React Native", target: "移动开发", type: "CHILD_OF" },
    { source: "Flutter", target: "移动开发", type: "CHILD_OF" },
    { source: "Swift", target: "移动开发", type: "CHILD_OF" },
    // CHILD_OF: 数据与AI
    { source: "TensorFlow", target: "数据与AI", type: "CHILD_OF" },
    { source: "PyTorch", target: "数据与AI", type: "CHILD_OF" },
    { source: "Pandas", target: "数据与AI", type: "CHILD_OF" },
    // ALIAS_OF
    { source: "React.js", target: "React", type: "ALIAS_OF" },
    { source: "ReactJS", target: "React", type: "ALIAS_OF" },
    { source: "Vue.js", target: "Vue", type: "ALIAS_OF" },
    { source: "TS", target: "TypeScript", type: "ALIAS_OF" },
    { source: "NextJS", target: "Next.js", type: "ALIAS_OF" },
    { source: "Golang", target: "Go", type: "ALIAS_OF" },
    { source: "NodeJS", target: "Node.js", type: "ALIAS_OF" },
    { source: "Postgres", target: "PostgreSQL", type: "ALIAS_OF" },
    { source: "Mongo", target: "MongoDB", type: "ALIAS_OF" },
    { source: "K8s", target: "Kubernetes", type: "ALIAS_OF" },
    { source: "RN", target: "React Native", type: "ALIAS_OF" },
    { source: "TF", target: "TensorFlow", type: "ALIAS_OF" },
  ],
};

export const demoCandidates: Candidate[] = [
  {
    id: "cand_001",
    country: "CN",
    timezone: "UTC+08:00",
    email: "zhang@example.com",
    languages: [{ code: "zh", level: "native" }, { code: "en", level: "fluent" }],
    skills: [{ name: "Python", level: 4 }, { name: "Data Analysis", level: 3 }, { name: "AI evaluation", level: 4 }],
    desired_roles: ["AI Evaluation Specialist", "Data Analyst"],
    minimum_hourly_rate: { amount: 15, currency: "USD" },
    availability_hours_per_week: 20,
    allowed_work_modes: ["remote"],
    notification_channels: ["email"],
    notification_frequency: "daily",
    excluded_companies: [],
    consent_status: "opted_in",
    created_at: "2026-07-10T08:00:00Z",
  },
  {
    id: "cand_002",
    country: "SG",
    timezone: "UTC+08:00",
    email: "li@example.com",
    languages: [{ code: "en", level: "native" }, { code: "zh", level: "working" }],
    skills: [{ name: "React", level: 5 }, { name: "TypeScript", level: 4 }, { name: "Figma", level: 3 }],
    desired_roles: ["Frontend Developer", "Product Designer"],
    minimum_hourly_rate: { amount: 25, currency: "USD" },
    availability_hours_per_week: 15,
    allowed_work_modes: ["remote", "hybrid"],
    notification_channels: ["email", "telegram"],
    notification_frequency: "weekly",
    excluded_companies: ["Unknown Merchant"],
    consent_status: "opted_out",
    created_at: "2026-07-12T10:30:00Z",
  },
  {
    id: "cand_003",
    country: "JP",
    timezone: "UTC+09:00",
    email: null,
    languages: [{ code: "ja", level: "native" }, { code: "en", level: "working" }],
    skills: [{ name: "Content Writing", level: 4 }, { name: "Translation", level: 5 }],
    desired_roles: ["Content Analyst", "Translator"],
    minimum_hourly_rate: { amount: 18, currency: "USD" },
    availability_hours_per_week: 10,
    allowed_work_modes: ["remote"],
    notification_channels: ["email"],
    notification_frequency: "daily",
    excluded_companies: [],
    consent_status: "not_requested",
    created_at: "2026-07-14T14:00:00Z",
  },
  {
    id: "cand_004",
    country: "CN",
    timezone: "UTC+08:00",
    email: "wang@example.com",
    languages: [{ code: "zh", level: "native" }, { code: "en", level: "fluent" }],
    skills: [{ name: "Python", level: 5 }, { name: "Machine Learning", level: 4 }, { name: "PostgreSQL", level: 3 }],
    desired_roles: ["Python Developer", "ML Engineer"],
    minimum_hourly_rate: { amount: 20, currency: "USD" },
    availability_hours_per_week: 25,
    allowed_work_modes: ["remote"],
    notification_channels: ["email", "in_app"],
    notification_frequency: "daily",
    excluded_companies: [],
    consent_status: "opted_in",
    created_at: "2026-07-08T06:00:00Z",
  },
];

export const demoMatches: MatchResult[] = [
  {
    id: "match_001",
    candidate_id: "cand_001",
    job_id: "job_001",
    job_title: "AI Evaluation Specialist",
    company_name: "Northstar Labs",
    total_score: 0.87,
    dimension_scores: { skills: 0.91, semantic: 0.85, language: 0.96, location: 0.88, compensation: 0.82, availability: 0.90, preference: 0.76, freshness: 0.93 },
    reasons: ["技能与职位要求高度匹配", "地区与工作时区满足要求", "薪资达到最低期望"],
    created_at: "2026-07-15T09:41:00Z",
  },
  {
    id: "match_002",
    candidate_id: "cand_001",
    job_id: "job_002",
    job_title: "Python Data Reviewer",
    company_name: "Atlas Data Co.",
    total_score: 0.79,
    dimension_scores: { skills: 0.84, semantic: 0.72, language: 0.90, location: 0.95, compensation: 0.72, availability: 0.70, preference: 0.68, freshness: 0.85 },
    reasons: ["Python 技能匹配", "全球可用职位", "薪资接近期望"],
    created_at: "2026-07-15T09:41:00Z",
  },
  {
    id: "match_003",
    candidate_id: "cand_004",
    job_id: "job_002",
    job_title: "Python Data Reviewer",
    company_name: "Atlas Data Co.",
    total_score: 0.91,
    dimension_scores: { skills: 0.95, semantic: 0.88, language: 0.88, location: 0.95, compensation: 0.80, availability: 1.00, preference: 0.90, freshness: 0.85 },
    reasons: ["Python 高级技能完全匹配", "全球可用职位", "角色偏好高度吻合"],
    created_at: "2026-07-15T09:42:00Z",
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "ntf_001",
    candidate_id: "cand_001",
    status: "pending_approval",
    entries: [
      { job_id: "job_001", job_title: "AI Evaluation Specialist", company_name: "Northstar Labs", score: 0.87, reasons: ["技能匹配", "地区匹配"] },
      { job_id: "job_002", job_title: "Python Data Reviewer", company_name: "Atlas Data Co.", score: 0.79, reasons: ["Python 技能匹配"] },
    ],
    created_at: "2026-07-15T09:43:00Z",
  },
  {
    id: "ntf_002",
    candidate_id: "cand_004",
    status: "approved",
    entries: [
      { job_id: "job_002", job_title: "Python Data Reviewer", company_name: "Atlas Data Co.", score: 0.91, reasons: ["Python 高级技能", "角色偏好吻合"] },
    ],
    approved_by: "operator@agenthub.local",
    approved_at: "2026-07-15T10:00:00Z",
    created_at: "2026-07-15T09:44:00Z",
  },
  {
    id: "ntf_003",
    candidate_id: "cand_001",
    status: "sent",
    entries: [
      { job_id: "job_004", job_title: "Part-time Product Designer", company_name: "Studio Commons", score: 0.72, reasons: ["地区匹配 SG"] },
    ],
    approved_by: "operator@agenthub.local",
    approved_at: "2026-07-14T16:00:00Z",
    sent_at: "2026-07-14T16:05:00Z",
    created_at: "2026-07-14T15:50:00Z",
  },
  {
    id: "ntf_004",
    candidate_id: "cand_002",
    status: "rejected",
    entries: [
      { job_id: "job_003", job_title: "Bilingual Content Analyst", company_name: "LinguaWorks", score: 0.65, reasons: ["语言部分匹配"] },
    ],
    approved_by: "operator@agenthub.local",
    approved_at: "2026-07-14T14:30:00Z",
    created_at: "2026-07-14T14:00:00Z",
  },
];

export const demoWorkflows: WorkflowRun[] = [
  {
    id: "wf_001",
    workflow_type: "source_sync",
    target_id: "src_001",
    status: "completed",
    actor: "scheduler",
    celery_task_id: "abc-123-def",
    steps: [
      { step_name: "fetch_source", status: "completed", retry_count: 0, started_at: "2026-07-15T09:20:00Z", completed_at: "2026-07-15T09:20:05Z" },
      { step_name: "validate_jobs", status: "completed", retry_count: 0, started_at: "2026-07-15T09:20:05Z", completed_at: "2026-07-15T09:20:08Z" },
      { step_name: "persist_jobs", status: "completed", retry_count: 0, started_at: "2026-07-15T09:20:08Z", completed_at: "2026-07-15T09:20:12Z" },
    ],
    created_at: "2026-07-15T09:20:00Z",
    completed_at: "2026-07-15T09:20:12Z",
  },
  {
    id: "wf_002",
    workflow_type: "matching",
    target_id: "cand_001",
    status: "completed",
    actor: "scheduler",
    celery_task_id: "ghi-456-jkl",
    steps: [
      { step_name: "load_candidate", status: "completed", retry_count: 0, started_at: "2026-07-15T09:41:00Z", completed_at: "2026-07-15T09:41:01Z" },
      { step_name: "hard_filter", status: "completed", retry_count: 0, started_at: "2026-07-15T09:41:01Z", completed_at: "2026-07-15T09:41:03Z" },
      { step_name: "score_and_rank", status: "completed", retry_count: 0, started_at: "2026-07-15T09:41:03Z", completed_at: "2026-07-15T09:41:05Z" },
    ],
    created_at: "2026-07-15T09:41:00Z",
    completed_at: "2026-07-15T09:41:05Z",
  },
  {
    id: "wf_003",
    workflow_type: "notification",
    target_id: "ntf_001",
    status: "running",
    actor: "operator@agenthub.local",
    celery_task_id: "mno-789-pqr",
    steps: [
      { step_name: "generate_digest", status: "completed", retry_count: 0, started_at: "2026-07-15T09:43:00Z", completed_at: "2026-07-15T09:43:02Z" },
      { step_name: "await_approval", status: "running", retry_count: 0, started_at: "2026-07-15T09:43:02Z" },
    ],
    created_at: "2026-07-15T09:43:00Z",
  },
  {
    id: "wf_004",
    workflow_type: "source_sync",
    target_id: "src_003",
    status: "failed",
    actor: "scheduler",
    celery_task_id: "stu-012-vwx",
    steps: [
      { step_name: "fetch_source", status: "completed", retry_count: 0, started_at: "2026-07-15T08:56:00Z", completed_at: "2026-07-15T08:56:04Z" },
      { step_name: "validate_jobs", status: "failed", retry_count: 2, error: "Connection timeout after 3 retries", started_at: "2026-07-15T08:56:04Z", completed_at: "2026-07-15T08:56:30Z" },
    ],
    created_at: "2026-07-15T08:56:00Z",
    completed_at: "2026-07-15T08:56:30Z",
  },
  {
    id: "wf_005",
    workflow_type: "notification_send",
    target_id: "ntf_003",
    status: "manual_review",
    actor: "system",
    steps: [
      { step_name: "validate_notification", status: "completed", retry_count: 0, started_at: "2026-07-14T16:05:00Z", completed_at: "2026-07-14T16:05:01Z" },
      { step_name: "send_email", status: "failed", retry_count: 1, error: "Email provider rate limit exceeded", started_at: "2026-07-14T16:05:01Z", completed_at: "2026-07-14T16:05:10Z" },
    ],
    created_at: "2026-07-14T16:05:00Z",
    completed_at: "2026-07-14T16:05:10Z",
  },
];

export const dashboardMetrics = [
  { label: "已注册 Agent", value: "01", delta: "平台运行正常", code: "AGT" },
  { label: "活跃职位", value: "1,284", delta: "+48 今日同步", code: "JOB" },
  { label: "候选人", value: "342", delta: "89% 已主动订阅", code: "USR" },
  { label: "待人工审批", value: "16", delta: "4 项高优先级", code: "APR" },
];

export const funnelData = [
  { label: "同步原始职位", value: 1642, width: 100 },
  { label: "通过风险检查", value: 1487, width: 91 },
  { label: "进入匹配池", value: 1284, width: 78 },
  { label: "产生高质匹配", value: 326, width: 42 },
  { label: "推荐已发送", value: 218, width: 29 },
];
